[package]
name = "ppphp-zed"
version = "2026.4.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "=0.7.0"
sha2 = "=0.10.9"

[dev-dependencies]
toml = "0.8"
tree-sitter = "0.25"
tree-sitter-ppphp = { git = "https://github.com/atatusoft-ltd/ppphp-language-server.git", rev = "394febc5f7a74c7ad46b0d0262ba5ad9a4017fb0" }
